version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: maxiimillian/test:frontend
    ports:
      - "3000:3000"
    env_file:
      ./frontend/.env
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: maxiimillian/test:backend
    ports:
      - "3002:3002"
    env_file:
      ./backend/.env
