name: Build and Publish

on:
  push:
    branches: [ production ]

jobs:   
  front-end:
    runs-on: ubuntu-18.04    
    env:      
      DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}      
      DOCKER_IMAGE_FRONT: "maxiimillian/test:frontend"
      DOCKER_IMAGE_BACK: "maxiimillian/test:backend"
      DOCKER_TARGET_PLATFORM: linux/arm/v7            

    steps:    
      - name: Checkout the code       
        uses: actions/checkout@v1      

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master    
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}



      - name: Run Build Backend
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/arm/v7
          tags: maxiimillian/test:backend
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

          

