name: Build and Publish

on:
  push:
    branches: [ production ]

jobs:   
  build-images:
    runs-on: ubuntu-18.04    
    env:      
      DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}      
      DOCKER_IMAGE_FRONT: "maxiimillian/test:frontend"
      DOCKER_IMAGE_BACK: "maxiimillian/test:backend"
      DOCKER_TARGET_PLATFORM: linux/arm/v7            

    steps:    
      - name: Checkout the code       
        uses: actions/checkout@v1      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master    
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Backend Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-backend
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx
      
      - name: Cache Backend Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-frontend
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Run Build Backend
        id: docker_build_back
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/arm/v7
          tags: maxiimillian/test:backend
          cache-from: type=local,src=/tmp/.buildx-cache-backend, mode=max
          cache-to: type=local,dest=/tmp/.buildx-cache-backend-new, mode=max
          build-args: |
            DB_PATH=${{ secrets.DB_PATH }}
            BOARD_DB_PATH=${{ secrets.BOARD_DB_PATH }}
            ALLOWED_URL=${{ secrets.ALLOWED_URL }}
            PORT=3001
              
      - name: Run Build Frontend
        id: docker_build_front
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/arm/v7
          tags: maxiimillian/test:frontend
          cache-from: type=local,src=/tmp/.buildx-cache-frontend, mode=max
          cache-to: type=local,dest=/tmp/.buildx-cache-frontend-new, mode=max
          build-args: |
            REACT_APP_API_URL=${{ secrets.API_URL }}
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-backend
          mv /tmp/.buildx-cache-backend-new /tmp/.buildx-cache-backend
          rm -rf /tmp/.buildx-cache-frontend
          mv /tmp/.buildx-cache-frontend-new /tmp/.buildx-cache-frontend
