name: Build and Publish

on:
  push:
    branches: [ production ]

jobs:   
  build-images:
    runs-on: ubuntu-18.04    
    env:      
      DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}      
      DOCKER_IMAGE_FRONT: "maxiimillian/test:frontend"
      DOCKER_IMAGE_BACK: "maxiimillian/test:backend"
      DOCKER_TARGET_PLATFORM: linux/arm/v7            

    steps:    
      - name: Checkout the code       
        uses: actions/checkout@v1      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master    
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run Build Backend
        id: docker_build_back
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/arm/v7
          tags: maxiimillian/test:backend
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          build-args: |
            DB_PATH=${{ secrets.DB_PATH }}
            BOARD_DB_PATH="./db.db"
            ALLOWED_URL=${{ secrets.ALLOWED_URL }}
              
      - name: Run Build Frontend
        id: docker_build_front
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/arm/v7
          tags: maxiimillian/test:frontend
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          build-args: |
            REACT_API_API_URL=${{ secrets.API_URL }}

