name: Build and Publish

on:
  push:
    branches: [ production ]

jobs:   
  front-end:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['4.0', '4.2', '4.4']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
 
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Docker build
      working-directory: ./frontend

      run: |
          docker build \
            --build-arg GIT_SHA=${{ github.sha }} \
            --build-arg GIT_REF=${{ github.ref }} \
            -t ${{ secrets.DOCKER_USERNAME }}/test:frontend .
 
    - name: Docker push
      run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/test:frontend
 
    - name: Docker logout
      run: docker logout