name: Build and Publish

on:
  push:
    branches: [ production ]

jobs:   
  front-end:
    runs-on: ubuntu-18.04    
    env:      
      DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}      
      DOCKER_IMAGE_FRONT: maxiimillian/test:frontend
      DOCKER_IMAGE_BACK: maxiimillian/test:backend
      DOCKER_TARGET_PLATFORM: linux/arm/v7            

    steps:    
      - name: Checkout the code       
        uses: actions/checkout@v1      

      - name: Set up Docker Buildx      
        uses: crazy-max/ghaction-docker-buildx@v1      
        with:        
          version: latest        
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run Build Backend
        if: success()
        run: |
          docker build -t $DOCKER_IMAGE_BACK ./backend/ \ 
          --build-arg DB_PATH=${{ secrets.DB_PATH }} \
          --build-arg BOARD_DB_PATH="./db.db" \
          --build-arg ALLOWED_URL=${{ secrets.ALLOWED_URL }}
          
              
      - name: Run Build Frontend
        if: success()      
        run: docker build -t $DOCKER_IMAGE_FRONT ./frontend/
      
      - name: Push Builds
        if: success()      
        run: |        
          docker push $DOCKER_IMAGE_FRONT
          docker push $DOCKER_IMAGE_BACK
