name: Build and Publish

on:
  push:
    branches: [ production ]

jobs:   
  front-end:
    runs-on: ubuntu-latest
 
    steps:
    - name: Set Build Date
      run: echo "::set-env name=BUILD_DATE::$(date +'%Y-%m-%d %H:%M:%S')"
 
    - name: Set Build Number
      run: echo "::set-env name=BUILD_VER::1.0.$GITHUB_RUN_NUMBER"
 
    - name: Set Image Name
      run: echo "::set-env name=IMG::test:frontend"
 
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
 
    - name: Docker build
      working-directory: ./backend
      run: |
          docker build \
            --build-arg GIT_SHA=${{ github.sha }} \
            --build-arg GIT_REF=${{ github.ref }} \
            --build-arg BUILD_DATE="${{ env.BUILD_DATE }}" \
            --build-arg BUILD_VER=${{ env.BUILD_VER }} \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMG }} .
 
    - name: Docker push
      run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMG }}
 
    - name: Docker logout
      run: docker logout