name: Build and Publish

on:
  push:
    branches: [ production ]

jobs:   
  front-end:
    runs-on: ubuntu-18.04    
    env:      
      DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}      
      DOCKER_IMAGE: maxiimillian/test:frontend

      DOCKER_TARGET_PLATFORM: linux/arm/v7                     
    steps:    
      - name: Checkout the code       
        uses: actions/checkout@v1      

      - name: Set up Docker Buildx      
        uses: crazy-max/ghaction-docker-buildx@v1      
        with:        
          version: latest        
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
              
      - name: Run Build   
        if: success()      
        run: |        
          docker build -t ${DOCKER_IMAGE} ./frontend/
          
      - name: Push Build  
        if: success()      
        run: |        
          docker push ${DOCKER_IMAGE}
