name: Build and Publish

on:
  push:
    branches: [ production ]

jobs:   
  front-end:
    runs-on: ubuntu-latest
 
    steps:
 
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
 
    - name: Docker build
      working-directory: ./frontend
      run: |
          docker build \
            --build-arg GIT_SHA=${{ github.sha }} \
            --build-arg GIT_REF=${{ github.ref }} \
            -t ${{ secrets.DOCKER_USERNAME }}/test:frontend .
 
    - name: Docker push
      run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/test:frontend
 
    - name: Docker logout
      run: docker logout