name: Deploy frontend to Amazon ECS

on:
  push:
    paths:
      - frontend/**
    branches:
      - production

env:             
  $USER: maxiimillian
  $DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN}}
  DOCKER_REPOSITORY: maxiimillian/test                
  IMAGE_TAG: frontend
  NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build, tag, and push image to Docker
      id: build-image
      run: |
        # Build a docker container and push it to docker
        docker build -t $DOCKER_REPOSITORY:$IMAGE_TAG --build-arg NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL ./frontend/
        docker push $DOCKER_REPOSITORY/:$IMAGE_TAG

    - name: Deploy new container on linode
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        scp -o StrictHostKeyChecking=no ./docker-compose.prod.yml root@${{ secrets.LINODE_IP_ADDRESS }}:/app
        ssh -o StrictHostKeyChecking=no root@${{ secrets.LINODE_IP_ADDRESS }} << 'ENDSSH'
          cd /app
          docker login -u $USER -p $DOCKER_TOKEN
          docker pull $DOCKER_REPOSITORY:$IMAGE_TAG
          sudo docker-compose -f docker-compose.prod.yml up -d
        ENDSSH

